# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M67HJ-ZXfHdbuIRd9Ovu4HQgZFKyqTOe
"""

!pip install bandit -q

# Commented out IPython magic to ensure Python compatibility.
# %%writefile vulnerable.py
# 
# import pickle
# import subprocess
# import hashlib
# 
# def load_data(file):
#     with open(file, "rb") as f:
#         return pickle.load(f)
# 
# def run_command(command):
#     return subprocess.call(command, shell=True)
# 
# def get_hash(data):
#     return hashlib.md5(data.encode()).hexdigest()
# 
# PASSWORD = "admin123"

!bandit vulnerable.py

# Commented out IPython magic to ensure Python compatibility.
# %%writefile fixed.py
# 
# import json
# import subprocess
# import hashlib
# import os
# 
# def load_data(file):
#     with open(file, "r") as f:
#         return json.load(f)
# 
# def run_command(command):
#     return subprocess.call(command, shell=False)
# 
# def get_hash(data):
#     return hashlib.sha256(data.encode()).hexdigest()
# 
# PASSWORD = os.environ.get("PASSWORD")

!bandit fixed.py