# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZAfzCU6l8vqy66jtsL9zyu8-6pZUCDNS
"""

from datetime import datetime

# Roles and permissions
ROLES = {
    "data_engineer": {"extract", "transform"},
    "data_scientist": {"train", "evaluate"},
    "ml_engineer": {"train", "deploy"},
    "admin": {"extract", "transform", "train", "evaluate", "deploy"},
    "viewer": {"view"}
}

# Audit log
audit_log = []


def check_access(role, action):
    if action in ROLES.get(role, set()):
        result = "ALLOW"
        print(f"[ALLOW] {role} -> {action}")
    else:
        result = "DENY"
        print(f"[DENY] {role} -> {action}")

    audit_log.append({
        "time": datetime.now().strftime("%H:%M:%S"),
        "role": role,
        "action": action,
        "result": result
    })


print("=== ML Pipeline RBAC ===")

check_access("admin", "deploy")
check_access("data_scientist", "train")
check_access("viewer", "train")
check_access("ml_engineer", "deploy")

print("=== Audit Log ===")

for log in audit_log:
    print(
        log["time"],
        "|", log["role"],
        "|", log["action"],
        "|", log["result"]
    )

print("=== Security Tests ===")

check_access("admin", "train")
check_access("viewer", "deploy")
check_access("data_engineer", "extract")
check_access("data_engineer", "deploy")

print("\n=== VERIFICATION ===")

for log in audit_log:
    print(log)